### ISSUE TITLE
Ensure ads.brave.com redirects to waitlist on iOS 

### ISSUE THREAD

**Issue by dlipeles** [brave/ads-ui#430] opened 2020-08-21 21:49 UTC
From #website - "Hi all, we’re seeing an issue with the redirect at https://ads.brave.com on mobile. On desktop, it redirects successfully; on mobile (at least on iOS), it gets stuck on a blank page. Tried turning Shields off and still doesn’t load, unfortunately. cc: @dan @Jacob Lamont @Amir @Ryan"

**Comment by tackley** [comment] 2021-07-21 10:35
Duplicate of #564

**Closed by tackley** 2021-07-21 10:35 UTC
